apiVersion: config.stackrox.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: 30-day-scan-age-copy
spec:
  policyName: 30-Day Scan Age (COPY)
  description: Alert on deployments with images that haven't been scanned in 30 days
  rationale: Out-of-date scans may not identify the most recent CVEs.
  remediation: Integrate a scanner with the StackRox Kubernetes Security Platform to trigger scans automatically.
  disabled: true
  categories:
    - Security Best Practices
    - Supply Chain Security
  lifecycleStages:
    - DEPLOY
  eventSource: NOT_APPLICABLE
  severity: MEDIUM_SEVERITY
  policySections:
    - policyGroups:
        - fieldName: Image Scan Age
          booleanOperator: OR
          values:
            - value: "30"
  criteriaLocked: false
  mitreVectorsLocked: false
  isDefault: false
